### ISSUE TITLE
Revealjs MOLSTAR

### ISSUE THREAD

**Issue by HankewieDanke** [jmbuhr/quarto-molstar#14]
Hey,
I love this plugin for quarto.

But I have following issue:
Molstar does not load any structure when rendering quarto to revealjs.

See below a minimal working example for html (working) and revealjs export:
```
---
title: "t"
subtitle: 't'
author: "t"
date: "2023/09/15"
to: html
---

{{< mol-rcsb 1f16 >}}
```

```
---
title: "t"
subtitle: 't'
author: "t"
date: "2023/09/15"
format:
    revealjs:
        theme: [serif,style.css]
        smaller: true
to: revealjs
---

{{< mol-rcsb 1f16 >}}
```

Maybe I am doing something wrong?
Thank you for your help :)

quarto version: 1.3.450
plugin: v0.1.2

**Comment by jmbuhr** [comment]
You don't need the extra `to: revealjs` (this will be passed directly to pandoc, maybe it circumvents the filter), if you remove it, it works.
If you need more styling  (by default the viewer might be a bit small in a presentation), check out https://github.com/jmbuhr/quarto-molstar/blob/main/presentation.qmd with https://github.com/jmbuhr/quarto-molstar/blob/main/presentation.css -> https://jmbuhr.de/quarto-molstar/presentation.html#/rcsb-pdb

**Comment by jmbuhr** [comment]
And thanks for the comprehensive reproducible example :)

**Comment by HankewieDanke** [comment]
Thank you for the quick response :)
This is working for the `mol-rcsb` case, but I still have problems when using a local file with `mol-url`.
Are there any spezificities I have to watch out for in the pdb formating?

**Comment by jmbuhr** [comment]
This example is working for me: https://jmbuhr.de/quarto-molstar/presentation.html#/local-pdb-file 
One step you can do for debugging is opening the developer tools (ctrl+shift+i in chromium bases browsers) and checking the console for things like:
![image](https://github.com/jmbuhr/quarto-molstar/assets/17450586/64cca825-294b-44dd-a5cb-4707f836f927)

This is what happens if I change the path to point to a non-existent file.

**Comment by jmbuhr** [comment]
If this issue doesn't appear  locally but only when deploying a website/document it may be a case of: https://github.com/jmbuhr/quarto-molstar/issues/7

I think quarto has recently added more functions for plugins to discover resources, so I should revisit this and add the resources automatically.

**Comment by jmbuhr** [comment]
If this doesn't work, can you send the pdb file? The pdb specification can indeed be a bit wild

**Comment by HankewieDanke** [comment]
Thanks a lot will give it a try.

So, I tried (and made sure files exist).
Reusing the headers from above (w/o `to: xxx` line), the problem still exists.
If I render to standard HTML everything works but with revealjs, it does not (see below `*.qmd` file and image).

```
---
title: "t"
subtitle: 't'
author: "t"
date: "2023/09/15"
format:
    revealjs:
        theme: [serif,style.css]
        smaller: true
molstar: embed
---

{{< mol-url ./pdbs/1F16.pdb >}}
```
It is simply the pdb file of `rcsb.org/structure/1f16`.
![Screenshot from 2023-09-15 15-50-26](https://github.com/jmbuhr/quarto-molstar/assets/45438167/fcfb5f94-edd1-4b37-af6e-d1d68f4f13ae)

The behaviour is the same w/ and w/o `molstar:embed`.

It is independent of 'locally' opening the file w/ browser or through a local standard webserver w/ `python -m http.server`.

As the PDB is directly from the rcsb, I fear it may not be a PDB spec problem (NMR structure w/ only protein).
